### PR TITLE
Upgrade comment test

### PR DESCRIPTION
**Pull request by gabriellaMT**

### CODE REVIEW

**Comment by 9gix** [comment]
Consider write documentation with doctype instead of commenting codes.

Also what are the changes that you made in general for this PR?

+1000 line of code -600 lines of code.

**Comment by gabriellaMT** [comment]
@9gix Can you give an example of doctype?
Commenting, also some refactoring (mainly on tests)

**Comment by 9gix** [comment]
Sorry, i mean [docstring ](https://en.wikipedia.org/wiki/Docstring)

**Comment by 9gix** [comment]
The reason why i recommend it because you can use it as part of your developer reference. You can automatically generate all of those documents later, such as by using [Sphinx](http://www.sphinx-doc.org/en/stable/)

**Pull request merged**
